/**
 * Running models on installments (client files "<Brand>_Running_Models_Developer_Details_Pakistan.pdf",
 * prepared 02 October 2026): the phones the financing partner (Palm app) offers on installments.
 * Official retail price (no dealer / discount price), physical RAM / storage, Pakistan colours.
 * Plans are priced with the site's installment calculator (prisma/seed.ts → installRunningModels).
 */
export type RunningModel = { brand: string; name: string; modelNo: string; price: number; ram: string; storage: string; colors: string };

export const RUNNING_MODELS: RunningModel[] = [
  { brand: "infinix", name: "Infinix GT 50 Pro", modelNo: "X6891", price: 189999, ram: "8GB", storage: "256GB", colors: "Black Abyss, Red Blaze, Silver Glacier" },
  { brand: "infinix", name: "Infinix NOTE 60 Pro", modelNo: "X6878", price: 125999, ram: "8GB", storage: "256GB", colors: "Mist Titanium, Deep Ocean Blue, Solar Orange, Mocha Brown, Torino Black, Frost Silver" },
  { brand: "infinix", name: "Infinix NOTE 60", modelNo: "X6879", price: 109999, ram: "8GB", storage: "256GB", colors: "Mist Titanium, Midnight Black, Fizz Blue, Rose Gold, Mocha Brown" },
  { brand: "infinix", name: "Infinix NOTE Edge", modelNo: "X6887", price: 99999, ram: "8GB", storage: "256GB", colors: "Lunar Titanium, Silk Green, Stellar Blue, Shadow Black, Orange" },
  { brand: "infinix", name: "Infinix Hot 70 Pro 5G", modelNo: "X6896", price: 89999, ram: "8GB", storage: "128GB", colors: "Night Pulse, Dive Blue, Depth Ring White, Mirage Green, Silk Glow Purple, Thermo Orange" },
  { brand: "infinix", name: "Infinix Note 50 Pro", modelNo: "X6855", price: 89999, ram: "12GB", storage: "256GB", colors: "Titanium Grey, Enchanted Purple, Racing Edition, Shadow Black" },
  { brand: "infinix", name: "Infinix Hot 60 Pro+", modelNo: "X6886", price: 84999, ram: "8GB", storage: "256GB", colors: "Sleek Black, Titanium Silver, Coral Tides, Misty Violet, Sonic Yellow, Moco Cyber Green" },
  { brand: "infinix", name: "Infinix Hot 60 Pro", modelNo: "X6885", price: 77999, ram: "8GB", storage: "128GB", colors: "Sleek Black, Titanium Silver, Coral Tides, Sapphire Blue, Jungle Breath, Orange Rose Valley" },
  { brand: "infinix", name: "Infinix Note 50", modelNo: "X6858", price: 74999, ram: "8GB", storage: "256GB", colors: "Titanium Grey, Ruby Red, Mountain Shade, Shadow Black" },
  { brand: "infinix", name: "Infinix Hot 70", modelNo: "X6895B", price: 68999, ram: "6GB", storage: "128GB", colors: "Night Pulse, Dive Blue, Silver Dancer, Thermo Orange, Green Texture, Quiet Violet" },
  { brand: "infinix", name: "Infinix ZERO 40", modelNo: "X6860", price: 62999, ram: "8GB", storage: "256GB", colors: "Misty Aqua, Rock Black, Blossom Glow" },
  { brand: "infinix", name: "Infinix Hot 60i", modelNo: "X6728", price: 61999, ram: "8GB", storage: "256GB", colors: "Sleek Black, Titanium Silver, Shadow Blue, Neon Red, Meadow Green, Soul Eye Purple" },
  { brand: "infinix", name: "Infinix Hot 60i", modelNo: "X6728B", price: 58999, ram: "6GB", storage: "128GB", colors: "Sleek Black, Titanium Silver, Shadow Blue, Neon Red, Meadow Green, Soul Eye Purple" },
  { brand: "infinix", name: "Infinix SMART 20", modelNo: "X6840", price: 41999, ram: "4GB", storage: "64GB", colors: "Shadow Black, Cloudline Blue, Polaris Titanium, Sunlike Orange" },
  { brand: "infinix", name: "Infinix Smart 10 Plus", modelNo: "X6725B", price: 33499, ram: "4GB", storage: "128GB", colors: "Sleek Black, Titanium Silver, Iris Blue, Ruby Red" },
  { brand: "infinix", name: "Infinix Smart 10", modelNo: "X6725", price: 29999, ram: "4GB", storage: "64GB", colors: "Sleek Black, Titanium Silver, Iris Blue, Twilight Gold" },
  { brand: "infinix", name: "Infinix Smart 10 HD", modelNo: "X6525D-N", price: 23499, ram: "2GB", storage: "64GB", colors: "Sleek Black, Titanium Grey, Jelly Green, Twilight Gold" },
  { brand: "itel", name: "itel Super 26 Ultra", modelNo: "S688LN", price: 45999, ram: "8GB", storage: "128GB", colors: "Sapphire Black Blue, Blush Pink Gold, Gilded White, Moonstone Silver" },
  { brand: "itel", name: "itel Power 80", modelNo: "P685L", price: 42999, ram: "4GB", storage: "128GB", colors: "Tundra Green, Rock Black, Lava Orange" },
  { brand: "itel", name: "itel City 200", modelNo: "C681L", price: 39999, ram: "4GB", storage: "128GB", colors: "Bass Black, Echo Silver, Vibe Purple, Melody Pink" },
  { brand: "itel", name: "itel A100", modelNo: "A673L", price: 34999, ram: "4GB", storage: "128GB", colors: "Fresh Green, Star Titanium, Shadow Titanium" },
  { brand: "itel", name: "itel Power 70", modelNo: "P673L", price: 34999, ram: "4GB", storage: "128GB", colors: "Marine, Natural Black, Star Titanium" },
  { brand: "itel", name: "itel S25", modelNo: "S685LN", price: 32999, ram: "6GB", storage: "128GB", colors: "Bromo Black, Mambo Mint, Sahara Gleam" },
  { brand: "itel", name: "itel A200+", modelNo: "A676L", price: 31999, ram: "3GB", storage: "128GB", colors: "Orange, Blue, Star Titanium" },
  { brand: "itel", name: "itel City 100", modelNo: "C671L", price: 28999, ram: "6GB", storage: "128GB", colors: "Fairy Purple, Navy Blue, Meteor Titanium" },
  { brand: "itel", name: "itel Power 65", modelNo: "P671L", price: 27999, ram: "4GB", storage: "128GB", colors: "Cyber Titanium, Cyber Black, Cyber Blaze" },
  { brand: "itel", name: "itel A100C", modelNo: "A6611L", price: 24999, ram: "4GB", storage: "64GB", colors: "Titanium Gold, Blaze Blue, Pure Black, Silk Green" },
  { brand: "itel", name: "itel A80", modelNo: "A671L", price: 21499, ram: "3GB", storage: "128GB", colors: "Sandstone Black, Glacier White, Wave Blue" },
  { brand: "itel", name: "itel A90", modelNo: "A6610L", price: 19999, ram: "4GB", storage: "128GB", colors: "Space Titanium, Starlit Black" },
  { brand: "itel", name: "itel A50", modelNo: "A667LP", price: 18999, ram: "4GB", storage: "64GB", colors: "Misty Aqua, Lime Green, Cyan Blue, Shimmer Gold" },
  { brand: "itel", name: "itel A50", modelNo: "A667L", price: 16999, ram: "3GB", storage: "64GB", colors: "Misty Aqua, Lime Green, Cyan Blue, Shimmer Gold" },
  { brand: "itel", name: "itel A50C", modelNo: "A669L", price: 14999, ram: "2GB", storage: "32GB", colors: "Dawn Blue, Sapphire Black, Misty Aqua" },
  { brand: "nubia", name: "nubia V80 Pro", modelNo: "Z2575", price: 55999, ram: "8GB", storage: "256GB", colors: "Midnight Black, Peach Fuzz" },
  { brand: "nubia", name: "nubia V80 Max", modelNo: "Z2577", price: 50999, ram: "8GB", storage: "256GB", colors: "Stardust Purple, Stellar Silver, Aurellia Gold, Sky Cyan, Space Black" },
  { brand: "nubia", name: "nubia A36", modelNo: "Z2472", price: 32999, ram: "4GB", storage: "64GB", colors: "Aqua Green, Black, Green, Nebula Black, Silver, Titanium Gold" },
  { brand: "oppo", name: "OPPO Reno15 Pro 5G", modelNo: "CPH2813", price: 249999, ram: "12GB", storage: "512GB", colors: "Aurora Blue, Dusk Brown" },
  { brand: "oppo", name: "OPPO Reno16 5G", modelNo: "CPH2865", price: 199999, ram: "12GB", storage: "256GB", colors: "Pop White, Dream Purple, Twilight Violet" },
  { brand: "oppo", name: "OPPO Reno15 5G", modelNo: "CPH2825", price: 179999, ram: "12GB", storage: "256GB", colors: "Twilight Blue, Aurora White" },
  { brand: "oppo", name: "OPPO Reno16 F 5G", modelNo: "CPH2859", price: 149999, ram: "8GB", storage: "256GB", colors: "Pop White, Dream Purple, Twilight Violet" },
  { brand: "oppo", name: "OPPO Reno15 F 5G", modelNo: "CPH2801", price: 134999, ram: "8GB", storage: "256GB", colors: "Aurora Blue, Twilight Blue" },
  { brand: "oppo", name: "OPPO A6s Pro", modelNo: "CPH2833", price: 119999, ram: "8GB", storage: "256GB", colors: "Eclipse Blue, Lumina Forest" },
  { brand: "oppo", name: "OPPO A6s", modelNo: "CPH2815", price: 99999, ram: "8GB", storage: "256GB", colors: "Cappuccino Brown, Ice White" },
  { brand: "oppo", name: "OPPO A6 Pro", modelNo: "CPH2799", price: 74999, ram: "8GB", storage: "256GB", colors: "Stellar Blue, Rosewood Red" },
  { brand: "oppo", name: "OPPO A6", modelNo: "CPH2817", price: 74999, ram: "8GB", storage: "256GB", colors: "Sapphire Blue, Aurora Gold" },
  { brand: "oppo", name: "OPPO A6k", modelNo: "CPH2891", price: 56999, ram: "4GB", storage: "128GB", colors: "Crystal Violet, Crystal Blue" },
  { brand: "oppo", name: "OPPO A6c", modelNo: "CPH2895", price: 43999, ram: "4GB", storage: "64GB", colors: "Stone Brown, Feather White" },
  { brand: "oppo", name: "OPPO A6x", modelNo: "CPH2819", price: 33999, ram: "4GB", storage: "64GB", colors: "Plum Purple, Ice Blue" },
];
